provider:
  discord:
    loginRedirectUrl: https://api.vyroai.com/v1/auth/discord/login/callback
    registerRedirectUrl: https://api.vyroai.com/v1/auth/discord/register/callback
  google:
    loginRedirectUrl: https://api.vyroai.com/v1/auth/google/login/callback
    registerRedirectUrl: https://api.vyroai.com/v1/auth/google/register/callback
  apple:
    loginRedirectUrl: https://api.vyroai.com/v1/auth/apple/login/callback
    registerRedirectUrl: https://api.vyroai.com/v1/auth/apple/register/callback
  instagram:
    loginRedirectUrl: https://api.vyroai.com/v1/auth/instagram/login/callback
    registerRedirectUrl: https://api.vyroai.com/v1/auth/instagram/register/callback

database:
  mysql:
    url: PLANETSCALE_DB





