// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type OauthAccountOauthProvider string

const (
	OauthAccountOauthProviderAPPLE     OauthAccountOauthProvider = "APPLE"
	OauthAccountOauthProviderGOOGLE    OauthAccountOauthProvider = "GOOGLE"
	OauthAccountOauthProviderINSTAGRAM OauthAccountOauthProvider = "INSTAGRAM"
	OauthAccountOauthProviderDISCORD   OauthAccountOauthProvider = "DISCORD"
)

func (e *OauthAccountOauthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthAccountOauthProvider(s)
	case string:
		*e = OauthAccountOauthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthAccountOauthProvider: %T", src)
	}
	return nil
}

type NullOauthAccountOauthProvider struct {
	OauthAccountOauthProvider OauthAccountOauthProvider
	Valid                     bool // Valid is true if OauthAccountOauthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthAccountOauthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.OauthAccountOauthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthAccountOauthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthAccountOauthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthAccountOauthProvider), nil
}

type ChatBot struct {
	ID             int64
	UserID         int64
	Title          string
	CharacterCount int32
	Private        bool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type ChatMessage struct {
	ID        int64
	ChatbotID int64
	Content   string
	Bot       bool
	CreatedBy int64
	CreatedAt sql.NullTime
}

type NewsletterSubscribed struct {
	ID    int64
	Email string
}

type OauthAccount struct {
	ID            int64
	UserID        int64
	OauthProvider NullOauthAccountOauthProvider
	AccountID     string
}

type Payment struct {
	ID              int64
	UserID          int64
	PlanID          int32
	Amount          string
	StripePaymentID string
	CreatedAt       sql.NullTime
}

type SubscriptionPlan struct {
	ID                 int32
	Name               string
	Description        string
	Price              string
	MessageLimit       int32
	CharacterLimit     int64
	Chatbot            int32
	MultipleFileUpload bool
	ShowBranding       bool
	ApiAccess          bool
}

type User struct {
	ID             int64
	Username       string
	Email          string
	Password       sql.NullString
	AvatarID       string
	Permission     int32
	FingerprintID  sql.NullString
	EmailConfirmed bool
	IsBanned       bool
	CreatedAt      time.Time
}

type UserSubscription struct {
	ID           int64
	UserID       int64
	PlanID       int32
	OpenaiApiKey sql.NullString
	ApiKey       string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
